networks:
  gastronomy-network:
    driver: bridge

volumes:
  mongo-vol: {}
  mongodb-config-vol: {}
  mongo-vol-test: {}
  mongodb-config-test-vol: {}

services:
  nextjs:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: gastronomy-nextjs:latest
    command: yarn dev
    ports:
      - "3001:3001"
    depends_on:
      - node-api
      - mongodb
      - mongodb-test
    networks:
      - gastronomy-network
    volumes:
      - ./client:/app
    env_file:
      - .env

  node-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: gastronomy-node-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - mongodb-test
    networks:
      - gastronomy-network
    command: sh -c "yarn dev"
    volumes:
      - ./server:/app

  mongodb:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27020:27017"
    volumes:
      - mongo-vol:/data/db
      - mongodb-config-vol:/data/configdb
    networks:
      - gastronomy-network

  mongodb-test:
    image: mongo
    restart: always
    env_file:
      - .env
    ports:
      - "27019:27017"
    volumes:
      - mongo-vol-test:/data/db
      - mongodb-config-test-vol:/data/configdb
    networks:
      - gastronomy-network
