import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { La_Belle_Aurore, Libre_Baskerville } from "next/font/google";
import { ReactNode } from "react";
import "../globals.css";
import { ReduxProvider } from "@/shared/lib/provider";
import { ThemeProvider } from "next-themes";
import { Footer, HeaderLoggedIn } from "@/shared/components";
import { Toaster } from "react-hot-toast";

const laBelleAurore = La_Belle_Aurore({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-la-belle-aurore"
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-libre-baskerville"
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${laBelleAurore.variable} ${libreBaskerville.variable} dark:bg-default-black bg-default-white dark:text-default-white text-default-black`}
      >
        <ReduxProvider>
          <ThemeProvider attribute="class">
            <HeaderLoggedIn isHome={false} />
            <Toaster />
            {children}
            <Footer />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
