name: CI Pipeline with Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Next.js image
        run: |
          docker build -t gastronomy-nextjs:latest -f client/Dockerfile ./client

      - name: Build Node API image
        run: |
          docker build -t gastronomy-node-api:latest -f server/Dockerfile ./server

      - name: Create Docker networks and volumes
        run: |
          docker network create gastronomy-network || true
          docker volume create mongo-vol || true
          docker volume create mongodb-config-vol || true
          docker volume create mongo-vol-test || true
          docker volume create mongodb-config-test-vol || true

      - name: Start MongoDB containers
        run: |
          docker run -d --name mongodb --network gastronomy-network -p 27018:27017 \
            -v mongo-vol:/data/db -v mongodb-config-vol:/data/configdb mongo

          docker run -d --name mongodb-test --network gastronomy-network -p 27019:27017 \
            -v mongo-vol-test:/data/db -v mongodb-config-test-vol:/data/configdb mongo

      - name: Start Node API container
        run: |
          docker run -d --name node-api --network gastronomy-network -p 3000:3000 \
            -v $GITHUB_WORKSPACE/server:/app --env-file $GITHUB_WORKSPACE/.env gastronomy-node-api:latest

      - name: Start Next.js container
        run: |
          docker run -d --name nextjs --network gastronomy-network -p 3001:3001 \
            -v $GITHUB_WORKSPACE/client:/app --env-file $GITHUB_WORKSPACE/.env gastronomy-nextjs:latest

      - name: Run tests
        run: |
          # Se necessário, rode comandos aqui para verificar o status da aplicação ou rodar testes
          # Exemplo: docker exec nextjs yarn test

      - name: Cleanup
        run: |
          docker stop nextjs node-api mongodb mongodb-test
          docker rm nextjs node-api mongodb mongodb-test
