name: Docker Build and Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   mongodb:
    #     image: mongo:latest
    #     ports:
    #       - 27020:27017
    #     volumes:
    #       - mongo-vol:/data/db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          cat <<EOF > .env
          AMBIENT=${{ secrets.AMBIENT }}
          NEXT_PUBLIC_URL=${{ secrets.NEXT_PUBLIC_URL }}
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          PORT=${{ secrets.PORT }}
          MONGO_DEV_URI=${{ secrets.MONGO_DEV_URI }}
          ACCESS_TOKEN_MAX_AGE=${{ secrets.ACCESS_TOKEN_MAX_AGE }}
          REFRESH_TOKEN_MAX_AGE=${{ secrets.REFRESH_TOKEN_MAX_AGE }}
          EMAIL_TOKEN_MAX_AGE=${{ secrets.EMAIL_TOKEN_MAX_AGE }}
          HTTP_ONLY=${{ secrets.HTTP_ONLY }}
          EMAIL_ADMIN=${{ secrets.EMAIL_ADMIN }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GHUB_CLIENT_ID=${{ secrets.GHUB_CLIENT_ID }}
          GHUB_CLIENT_SECRET=${{ secrets.GHUB_CLIENT_SECRET }}
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          MONGO_TEST_URI=${{ secrets.MONGO_TEST_URI }}
          TEST_TOKEN=${{ secrets.TEST_TOKEN }}
          ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
          REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}
          EMAIL_TOKEN_SECRET=${{ secrets.EMAIL_TOKEN_SECRET }}
          EOF

      - name: Start Docker containers
        run: docker-compose up --build -d
        # timeout-minutes: 10

      # - name: Tail Node API container logs
      #   run: docker-compose logs -f node-api

      - name: Debug running containers
        run: docker-compose ps

      - name: List files inside server directory
        run: docker-compose exec node-api sh -c "ls -l"

      # - name: List files inside server directory
      #   run: docker-compose exec node-api sh -c "ls -l /usr/src/app/server"

      - name: Display package.json content
        run: docker-compose exec node-api sh -c "cat package.json"

      - name: Debug running containers
        run: docker-compose ps

      - name: Run tests in Node.js API container
        run: |
          docker-compose exec node-api sh -c "yarn test"

      - name: Debug running containers
        run: docker ps -a

      - name: Check Next.js container logs
        run: docker-compose logs nextjs

      - name: Run tests in Next.js container
        run: |
          docker-compose exec nextjs sh -c "yarn test"
