name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # MongoDB to dev
      mongodb:
        image: mongo
        ports:
          - 27018:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - mongo-vol:/data/db
        networks:
          - gastronomy-network

      # MongoDB to tests
      mongodb-test:
        image: mongo
        ports:
          - 27019:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - mongo-vol-test:/data/db
        networks:
          - gastronomy-network

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and run containers using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Run tests
        run: |
          docker-compose exec node-api sh -c "yarn test"

      - name: Shut down containers
        run: |
          docker-compose down

    networks:
      gastronomy-network:
        driver: bridge

    volumes:
      mongo-vol: {}
      mongodb-config-vol: {}
      mongo-vol-test: {}
      mongodb-config-test-vol: {}
